language: node_js
node_js:
 - "node"
env: 
  - CODECLIMATE_REPO_TOKEN=096eba8d4801fa3d74634b4f237045a7c15239d0e6c454d992689cab00ab7593
before_script:
  - psql -c "CREATE DATABASE travis;" -U postgres
after_success:
  - npm run coverage
